# Introduction {#intro}


## R Packages 

Here are all of the [`R`](#def:rstats) packages used in this book. If you would like to download and compile this book on your own system, this chunk will install and load all of the necessary packages for you. If you have problems with installation of any of these packages, this is probably due to an individual computer or `R` version issue. If you experience any installation problems, the best thing to do is to search for the error message you get on the web to see if anyone else has already solved your problem. If the package you are having troubles with has a [GitHub](https://github.com/) repository, you should search its [Issues](https://github.com/issues) to see if the author of the package has encountered and/or solved your problem before. If not, [community.rstudio.com](https://community.rstudio.com/) and [Stack Overflow](https://stackoverflow.com/questions/tagged/r) tend to be the most trustworthy sources of troubleshooting information. If all else fails, you can post an issue on the Github repo for this book (INSERT LINK). However, this should be your last resort: the authors of this book are subject matter experts, not necessarily computer debugging experts for your specific system and installation.  

```{r all_packages, eval = FALSE}
options(repos = "http://cran.us.r-project.org")

# check if a package is installed, if not install it from cran
install_cran_missing <- function(pkgname){
  if(class(pkgname) != "character"){
    stop("pkgname must be a character")
  }
  if (!require(pkgname, character.only = TRUE, quietly = TRUE)){
    install.packages(pkgname, dep = T)
    if(!require(pkgname,character.only = TRUE)) stop("CRAN Package not found")
  }
}
# check if a package is installed, if not install it from Github
install_dev_missing <- function(pkgname, ghuser){
  if(class(pkgname) != "character"){
    stop("pkgname must be a character")
  }
  if (!require(pkgname, character.only = TRUE, quietly = TRUE)){
    repo <- paste(ghuser, pkgname, sep ='/')
    devtools::install_github(repo)
    if(!require(pkgname,character.only = TRUE)) stop("Github repo for package not found")
  }
}
# need devtools to get some packages 
install_cran_missing("devtools")
# packages used throughout the book 
install_cran_missing("tidyverse") # or install_dev_missing("tidyverse", "tidyverse")
install_dev_missing("gt", "rstudio") 

# Chapter 3: DNA Validation
# Watch out for dependency issues with RGtk2...
install_cran_missing("strvalidator")

# Chapter 4: DNA Mixture
# TBD

# Chapter 5: Glass
install_cran_missing("caret")
install_cran_missing("GGally")
install_cran_missing("stringr")
install_dev_missing("patchwork", "thomasp85")
install_dev_missing("csafethemes", "csafe-isu")


# Chapter 6: Shoe
# TBD

# Chapter 7: Bullets
install_cran_missing("x3ptools") # or install_dev_missing("x3ptools", "heike")
install_cran_missing("randomForest") 
install_dev_missing("bulletxtrctr", "heike")

# Chapter 8: Casings
if (!requireNamespace("BiocManager", quietly = TRUE)){
    install.packages("BiocManager")
  }
BiocManager::install("EBImage", version = "3.8")
install_dev_missing("cartridges", "xhtai")

# Chapter 9: Digital 
# TBD 

# Chapter 10: Fingerprints
install_cran_missing("bmp")
install_cran_missing("kableExtra")

# Chapter 11: Handwriting 
# TBD

# Chapter 12: Toolmarks
# TBD

# Chapter 13: Human Factors
install_dev_missing("blackboxstudyR", "aluby")
install_cran_missing("rstan")
install_cran_missing("RColorBrewer")
install_cran_missing("gridExtra")
install_cran_missing("gghighlight")
install_cran_missing("ggpubr")
```

## Terminology and Definitions

In the appendix, you will find a dedicated [Glossary](#glossary) section. The terms are listed in the order that they appear in the book. Throughout the book, the first time you encounter a glossary phrase, the phrase will be a link to the glossary entry, similar to the way Wikipedia handles their links. If you feel a term is lacking a glossary entry, please file an issue on Github. (INSERT LINK HERE). 
