--- 
title: "Open Forensic Science in R"
author: "Editors: Sam Tyner, Heike Hofmann"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [bib/book.bib, bib/packages.bib, bib/glass.bib, bib/shoe.bib, bib/fingerprint.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This book is for anyone looking to do forensic science analysis in a data-driven and open way."
---

# Prologue {.unnumbered}

This book is for anyone looking to do forensic science analysis in a data-driven and open way. Whether you are a student, teacher, or scientist, this book is for you. We take the latest research and show you how to do forensic science in `R`. The book makes some assumptions about you: 

1. **You have some experience with `R`.** We don't assume you're an expert by any means, but we do assume you're comfortable enough with it to install & library packages, load data, identify different data structures, and to follow along with the code we present in each chapter. If you need help getting started with `R`, check out [this free course from DataCamp](https://www.datacamp.com/courses/free-introduction-to-r). You can install `R` for Windows, Mac, and Linux [here](https://cloud.r-project.org/) for free. We also recommend you install [RStudio](https://www.rstudio.com/products/rstudio/download/), the wonderful free IDE (Integrated Development Environment) for `R`. If you want a deeper dive into `R`, take a walk through [R for Data Science](http://r4ds.had.co.nz/). If you really want to explore the depths, [Advanced R](https://adv-r.hadley.nz/) is an excellent resource. 
2. **You are interested in forensic science.** Hopefully that's why you're here! You may only be interested in DNA or bullets, so we've split the book up into chapters by forensic science subfield. You also don't have to be an expert in the field. We will explain the basics of the field in the introduction of each chapter. You can also download this book **(INSERT LINK)** and follow along on your own system.
3. **You care about open source software.** This doesn't really affect your ability to read this book, but it's a nice quality to have. The purpose of this book is to make forensic science more accessible. Right now, most databases, algorithms, and programs that get used every day in forensic science are proprietary. This means that only the owners know how these systems work, how they were made, and what the source code looks like. This closed approach has lead to [miscarriages of justice](https://www.propublica.org/article/thousands-of-criminal-cases-in-new-york-relied-on-disputed-dna-testing-techniques). With this free online book that relies *solely* on open-source software for analysis, we hope to demonstrate the impact open source software can have on forensic science, both in research and in practice. And in this spirit of openness, we ask that you contribute if you find an error or want to add a chapter on a topic we didn't cover. You can open an issue **(INSERT LINK)** or fork the book's Github repository **(INSERT LINK)** and submit your changes via a pull request. 


# About the Authors {.unnumbered}


## Sam Tyner {-}

Sam is a Postdoctoral Research Associate in the [Center for Statistics and Applications in Forensic Evidence](https://forensicstats.org/) (CSAFE) at [Iowa State University](https://www.iastate.edu/) (ISU). She earned her Ph.D. in Statistics from ISU in 2017. In 2018, she received a fellowship from [rOpenSci](https://ropensci.org/blog/2018/02/14/announcing-2018-ropensci-fellows/) to create this free book for anyone interested in open source forensic science.

## Heike Hofmann  {-}

Heike is a Professor of Statistics at Iowa State University. 

## Soyoung Park {-}

Soyoung is ...

## Eric Hare {-}

Eric is the Chief Data Scientist at [Omni Analytics](https://omnianalytics.io/). He earned his Ph.D. in Statistics from Iowa State University in 2017. (?) 

## Xiao Hui Tai {-}

Xiao Hui is ...

## Karen Pan {-}

Karen is ...

## Amanda Luby {-}

Amanda is ... 


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
