<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 7 Trace glass evidence: chemical composition | Open Forensic Science in R</title>
  <meta name="description" content="This book is for anyone looking to do forensic science analysis in a data-driven and open way.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 7 Trace glass evidence: chemical composition | Open Forensic Science in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book is for anyone looking to do forensic science analysis in a data-driven and open way." />
  <meta name="github-repo" content="sctyner/openforscir" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Trace glass evidence: chemical composition | Open Forensic Science in R" />
  
  <meta name="twitter:description" content="This book is for anyone looking to do forensic science analysis in a data-driven and open way." />
  

<meta name="author" content="Editor: Sam Tyner, Ph.D.">


<meta name="date" content="2019-06-22">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="shoe.html">
<link rel="next" href="decision-making.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.5/datatables.js"></script>
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.16/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>



<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Open Forensic Science in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prologue</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the Authors</a><ul>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#sam-tyner-ph.d."><i class="fa fa-check"></i>Sam Tyner, Ph.D. </a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#heike-hofmann-ph.d."><i class="fa fa-check"></i>Heike Hofmann, Ph.D. </a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#soyoung-park-ph.d."><i class="fa fa-check"></i>Soyoung Park, Ph.D. </a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#eric-hare-ph.d."><i class="fa fa-check"></i>Eric Hare, Ph.D. </a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#xiao-hui-tai"><i class="fa fa-check"></i>Xiao Hui Tai</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#karen-kafadar-ph.d."><i class="fa fa-check"></i>Karen Kafadar, Ph.D. </a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#karen-pan"><i class="fa fa-check"></i>Karen Pan</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#amanda-luby"><i class="fa fa-check"></i>Amanda Luby</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html#ganesh-krishnan-m.sc."><i class="fa fa-check"></i>Ganesh Krishnan, M.Sc.</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#r-packages"><i class="fa fa-check"></i><b>1.1</b> R Packages</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#terminology-and-definitions"><i class="fa fa-check"></i><b>1.2</b> Terminology and Definitions</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#forscip"><i class="fa fa-check"></i><b>1.3</b> Forensic Science Problems</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="dnaval.html"><a href="dnaval.html"><i class="fa fa-check"></i><b>2</b> Validation of DNA Interpretation Systems</a><ul>
<li class="chapter" data-level="" data-path="dnaval.html"><a href="dnaval.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="2.1" data-path="dnaval.html"><a href="dnaval.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a><ul>
<li class="chapter" data-level="2.1.1" data-path="dnaval.html"><a href="dnaval.html#procedure-for-dna-analysis-using-strs"><i class="fa fa-check"></i><b>2.1.1</b> Procedure for DNA Analysis using STRs</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="dnaval.html"><a href="dnaval.html#data"><i class="fa fa-check"></i><b>2.2</b> Data</a></li>
<li class="chapter" data-level="2.3" data-path="dnaval.html"><a href="dnaval.html#r-package"><i class="fa fa-check"></i><b>2.3</b> R Package</a></li>
<li class="chapter" data-level="2.4" data-path="dnaval.html"><a href="dnaval.html#drawing-conclusions"><i class="fa fa-check"></i><b>2.4</b> Drawing Conclusions</a><ul>
<li class="chapter" data-level="2.4.1" data-path="dnaval.html"><a href="dnaval.html#stutter-ratio"><i class="fa fa-check"></i><b>2.4.1</b> Stutter ratio</a></li>
<li class="chapter" data-level="2.4.2" data-path="dnaval.html"><a href="dnaval.html#heterozygote-balance"><i class="fa fa-check"></i><b>2.4.2</b> Heterozygote balance</a></li>
<li class="chapter" data-level="2.4.3" data-path="dnaval.html"><a href="dnaval.html#inter-locus-balance"><i class="fa fa-check"></i><b>2.4.3</b> Inter-locus balance</a></li>
<li class="chapter" data-level="2.4.4" data-path="dnaval.html"><a href="dnaval.html#stochastic-threshold"><i class="fa fa-check"></i><b>2.4.4</b> Stochastic threshold</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="dnaval.html"><a href="dnaval.html#case-study"><i class="fa fa-check"></i><b>2.5</b> Case Study</a><ul>
<li class="chapter" data-level="2.5.1" data-path="dnaval.html"><a href="dnaval.html#get-the-data"><i class="fa fa-check"></i><b>2.5.1</b> Get the data</a></li>
<li class="chapter" data-level="2.5.2" data-path="dnaval.html"><a href="dnaval.html#check-the-stutter-ratio"><i class="fa fa-check"></i><b>2.5.2</b> Check the stutter ratio</a></li>
<li class="chapter" data-level="2.5.3" data-path="dnaval.html"><a href="dnaval.html#check-heterozygote-balance-intra-locus-balance"><i class="fa fa-check"></i><b>2.5.3</b> Check heterozygote balance (intra-locus balance)</a></li>
<li class="chapter" data-level="2.5.4" data-path="dnaval.html"><a href="dnaval.html#check-inter-locus-balance"><i class="fa fa-check"></i><b>2.5.4</b> Check inter-locus balance</a></li>
<li class="chapter" data-level="2.5.5" data-path="dnaval.html"><a href="dnaval.html#check-stochastic-threshold"><i class="fa fa-check"></i><b>2.5.5</b> Check stochastic threshold</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bullets.html"><a href="bullets.html"><i class="fa fa-check"></i><b>3</b> Firearms: bullets</a><ul>
<li class="chapter" data-level="3.1" data-path="bullets.html"><a href="bullets.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="bullets.html"><a href="bullets.html#data-1"><i class="fa fa-check"></i><b>3.2</b> Data</a></li>
<li class="chapter" data-level="3.3" data-path="bullets.html"><a href="bullets.html#r-packages-1"><i class="fa fa-check"></i><b>3.3</b> R Package(s)</a><ul>
<li class="chapter" data-level="3.3.1" data-path="bullets.html"><a href="bullets.html#x3ptools"><i class="fa fa-check"></i><b>3.3.1</b> x3ptools</a></li>
<li class="chapter" data-level="3.3.2" data-path="bullets.html"><a href="bullets.html#bulletxtrctr"><i class="fa fa-check"></i><b>3.3.2</b> <code>bulletxtrctr</code></a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="bullets.html"><a href="bullets.html#drawing-conclusions-1"><i class="fa fa-check"></i><b>3.4</b> Drawing Conclusions</a></li>
<li class="chapter" data-level="3.5" data-path="bullets.html"><a href="bullets.html#case-study-1"><i class="fa fa-check"></i><b>3.5</b> Case Study</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="casings.html"><a href="casings.html"><i class="fa fa-check"></i><b>4</b> Firearms: casings</a><ul>
<li class="chapter" data-level="4.1" data-path="casings.html"><a href="casings.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="casings.html"><a href="casings.html#data-2"><i class="fa fa-check"></i><b>4.2</b> Data</a></li>
<li class="chapter" data-level="4.3" data-path="casings.html"><a href="casings.html#r-packages-2"><i class="fa fa-check"></i><b>4.3</b> R Package(s)</a></li>
<li class="chapter" data-level="4.4" data-path="casings.html"><a href="casings.html#casings-conclusions"><i class="fa fa-check"></i><b>4.4</b> Drawing Conclusions</a></li>
<li class="chapter" data-level="4.5" data-path="casings.html"><a href="casings.html#casings-caseStudy"><i class="fa fa-check"></i><b>4.5</b> Case Study</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="fingerprints.html"><a href="fingerprints.html"><i class="fa fa-check"></i><b>5</b> Latent Fingerprints</a><ul>
<li class="chapter" data-level="5.1" data-path="fingerprints.html"><a href="fingerprints.html#introduction-3"><i class="fa fa-check"></i><b>5.1</b> Introduction</a><ul>
<li class="chapter" data-level="5.1.1" data-path="fingerprints.html"><a href="fingerprints.html#contrast-gradient-quality-measurement"><i class="fa fa-check"></i><b>5.1.1</b> Contrast Gradient Quality Measurement</a></li>
<li class="chapter" data-level="5.1.2" data-path="fingerprints.html"><a href="fingerprints.html#contrast-gradient-quality-measurement-illustration"><i class="fa fa-check"></i><b>5.1.2</b> Contrast Gradient Quality Measurement Illustration</a></li>
<li class="chapter" data-level="5.1.3" data-path="fingerprints.html"><a href="fingerprints.html#test-for-usable-quality"><i class="fa fa-check"></i><b>5.1.3</b> Test for Usable Quality</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="fingerprints.html"><a href="fingerprints.html#data-3"><i class="fa fa-check"></i><b>5.2</b> Data</a><ul>
<li class="chapter" data-level="5.2.1" data-path="fingerprints.html"><a href="fingerprints.html#ace-v-and-afis"><i class="fa fa-check"></i><b>5.2.1</b> ACE-V and AFIS</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="fingerprints.html"><a href="fingerprints.html#r-package-1"><i class="fa fa-check"></i><b>5.3</b> R Package</a></li>
<li class="chapter" data-level="5.4" data-path="fingerprints.html"><a href="fingerprints.html#drawing-conclusions-2"><i class="fa fa-check"></i><b>5.4</b> Drawing Conclusions</a></li>
<li class="chapter" data-level="5.5" data-path="fingerprints.html"><a href="fingerprints.html#case-study-2"><i class="fa fa-check"></i><b>5.5</b> Case Study</a><ul>
<li class="chapter" data-level="" data-path="fingerprints.html"><a href="fingerprints.html#acknowledgements-1"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="shoe.html"><a href="shoe.html"><i class="fa fa-check"></i><b>6</b> Shoe Outsole Impression Evidence</a><ul>
<li class="chapter" data-level="6.1" data-path="shoe.html"><a href="shoe.html#introduction-4"><i class="fa fa-check"></i><b>6.1</b> Introduction</a><ul>
<li class="chapter" data-level="6.1.1" data-path="shoe.html"><a href="shoe.html#sources-of-variability-in-shoe-outsole-impressions"><i class="fa fa-check"></i><b>6.1.1</b> Sources of variability in shoe outsole impressions</a></li>
<li class="chapter" data-level="6.1.2" data-path="shoe.html"><a href="shoe.html#current-practice"><i class="fa fa-check"></i><b>6.1.2</b> Current practice</a></li>
<li class="chapter" data-level="6.1.3" data-path="shoe.html"><a href="shoe.html#goal-of-this-chapter"><i class="fa fa-check"></i><b>6.1.3</b> Goal of this chapter</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="shoe.html"><a href="shoe.html#data-4"><i class="fa fa-check"></i><b>6.2</b> Data</a><ul>
<li class="chapter" data-level="6.2.1" data-path="shoe.html"><a href="shoe.html#data-collection"><i class="fa fa-check"></i><b>6.2.1</b> Data collection</a></li>
<li class="chapter" data-level="6.2.2" data-path="shoe.html"><a href="shoe.html#transformation-of-shoe-image"><i class="fa fa-check"></i><b>6.2.2</b> Transformation of shoe image</a></li>
<li class="chapter" data-level="6.2.3" data-path="shoe.html"><a href="shoe.html#definition-of-classes"><i class="fa fa-check"></i><b>6.2.3</b> Definition of classes</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="shoe.html"><a href="shoe.html#r-packages-3"><i class="fa fa-check"></i><b>6.3</b> R Package(s)</a><ul>
<li class="chapter" data-level="6.3.1" data-path="shoe.html"><a href="shoe.html#one-subarea-matching"><i class="fa fa-check"></i><b>6.3.1</b> One subarea matching</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="shoe.html"><a href="shoe.html#drawing-conclusions-3"><i class="fa fa-check"></i><b>6.4</b> Drawing Conclusions</a></li>
<li class="chapter" data-level="6.5" data-path="shoe.html"><a href="shoe.html#shoe-case-study"><i class="fa fa-check"></i><b>6.5</b> Case Study</a><ul>
<li class="chapter" data-level="6.5.1" data-path="shoe.html"><a href="shoe.html#sec:shoeqk1"><i class="fa fa-check"></i><b>6.5.1</b> Compare <span class="math inline">\(Q\)</span> and <span class="math inline">\(K_1\)</span></a></li>
<li class="chapter" data-level="6.5.2" data-path="shoe.html"><a href="shoe.html#compare-q-and-k_2"><i class="fa fa-check"></i><b>6.5.2</b> Compare <span class="math inline">\(Q\)</span> and <span class="math inline">\(K_2\)</span></a></li>
<li class="chapter" data-level="6.5.3" data-path="shoe.html"><a href="shoe.html#interpreting-comparisons-between-q-k_1-and-q-k_2"><i class="fa fa-check"></i><b>6.5.3</b> Interpreting Comparisons between <span class="math inline">\(Q, K_1\)</span> and <span class="math inline">\(Q, K_2\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="glass.html"><a href="glass.html"><i class="fa fa-check"></i><b>7</b> Trace glass evidence: chemical composition</a><ul>
<li class="chapter" data-level="7.1" data-path="glass.html"><a href="glass.html#introduction-5"><i class="fa fa-check"></i><b>7.1</b> Introduction</a><ul>
<li class="chapter" data-level="7.1.1" data-path="glass.html"><a href="glass.html#problems-of-interest"><i class="fa fa-check"></i><b>7.1.1</b> Problems of interest</a></li>
<li class="chapter" data-level="7.1.2" data-path="glass.html"><a href="glass.html#current-practice-1"><i class="fa fa-check"></i><b>7.1.2</b> Current practice</a></li>
<li class="chapter" data-level="7.1.3" data-path="glass.html"><a href="glass.html#comparing-glass-fragments"><i class="fa fa-check"></i><b>7.1.3</b> Comparing glass fragments</a></li>
<li class="chapter" data-level="7.1.4" data-path="glass.html"><a href="glass.html#goal-of-this-chapter-1"><i class="fa fa-check"></i><b>7.1.4</b> Goal of this chapter</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="glass.html"><a href="glass.html#data-5"><i class="fa fa-check"></i><b>7.2</b> Data</a><ul>
<li class="chapter" data-level="7.2.1" data-path="glass.html"><a href="glass.html#chemical-composition-of-glass"><i class="fa fa-check"></i><b>7.2.1</b> Chemical composition of glass</a></li>
<li class="chapter" data-level="7.2.2" data-path="glass.html"><a href="glass.html#data-source"><i class="fa fa-check"></i><b>7.2.2</b> Data source</a></li>
<li class="chapter" data-level="7.2.3" data-path="glass.html"><a href="glass.html#data-structure"><i class="fa fa-check"></i><b>7.2.3</b> Data structure</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="glass.html"><a href="glass.html#glass_rpkgs"><i class="fa fa-check"></i><b>7.3</b> R Packages</a></li>
<li class="chapter" data-level="7.4" data-path="glass.html"><a href="glass.html#drawing-conclusions-4"><i class="fa fa-check"></i><b>7.4</b> Drawing Conclusions</a></li>
<li class="chapter" data-level="7.5" data-path="glass.html"><a href="glass.html#case-study-3"><i class="fa fa-check"></i><b>7.5</b> Case Study</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="decision-making.html"><a href="decision-making.html"><i class="fa fa-check"></i><b>8</b> Decision-making in Forensic Identification Tasks</a><ul>
<li class="chapter" data-level="8.1" data-path="decision-making.html"><a href="decision-making.html#introduction-6"><i class="fa fa-check"></i><b>8.1</b> Introduction</a><ul>
<li class="chapter" data-level="8.1.1" data-path="decision-making.html"><a href="decision-making.html#irt"><i class="fa fa-check"></i><b>8.1.1</b> A Brief Overview of Item Response Models</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="decision-making.html"><a href="decision-making.html#humans-data"><i class="fa fa-check"></i><b>8.2</b> Data</a></li>
<li class="chapter" data-level="8.3" data-path="decision-making.html"><a href="decision-making.html#rpackages"><i class="fa fa-check"></i><b>8.3</b> R Packages</a></li>
<li class="chapter" data-level="8.4" data-path="decision-making.html"><a href="decision-making.html#humans-conclusions"><i class="fa fa-check"></i><b>8.4</b> Drawing Conclusions</a></li>
<li class="chapter" data-level="8.5" data-path="decision-making.html"><a href="decision-making.html#casestudy"><i class="fa fa-check"></i><b>8.5</b> Case Study</a><ul>
<li class="chapter" data-level="8.5.1" data-path="decision-making.html"><a href="decision-making.html#fitting-the-irt-model"><i class="fa fa-check"></i><b>8.5.1</b> Fitting the IRT model</a></li>
<li class="chapter" data-level="8.5.2" data-path="decision-making.html"><a href="decision-making.html#irt-complements-an-error-rate-analysis"><i class="fa fa-check"></i><b>8.5.2</b> IRT complements an error rate analysis</a></li>
<li class="chapter" data-level="8.5.3" data-path="decision-making.html"><a href="decision-making.html#scoring-method-affects-proficiency-estimates"><i class="fa fa-check"></i><b>8.5.3</b> Scoring method affects proficiency estimates</a></li>
<li class="chapter" data-level="8.5.4" data-path="decision-making.html"><a href="decision-making.html#discussion"><i class="fa fa-check"></i><b>8.5.4</b> Discussion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="acknowledgements-2.html"><a href="acknowledgements-2.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="glossary.html"><a href="glossary.html"><i class="fa fa-check"></i><b>A</b> Glossary</a><ul>
<li class="chapter" data-level="A.1" data-path="glossary.html"><a href="glossary.html#introduction-7"><i class="fa fa-check"></i><b>A.1</b> Introduction</a></li>
<li class="chapter" data-level="A.2" data-path="glossary.html"><a href="glossary.html#validation-of-dna-interpretation-systems"><i class="fa fa-check"></i><b>A.2</b> Validation of DNA Interpretation Systems</a></li>
<li class="chapter" data-level="A.3" data-path="glossary.html"><a href="glossary.html#firearms-bullets"><i class="fa fa-check"></i><b>A.3</b> Firearms: bullets</a></li>
<li class="chapter" data-level="A.4" data-path="glossary.html"><a href="glossary.html#firearms-casings"><i class="fa fa-check"></i><b>A.4</b> Firearms: casings</a></li>
<li class="chapter" data-level="A.5" data-path="glossary.html"><a href="glossary.html#latent-fingerprints"><i class="fa fa-check"></i><b>A.5</b> Latent Fingerprints</a></li>
<li class="chapter" data-level="A.6" data-path="glossary.html"><a href="glossary.html#shoe-outsole-impression-evidence"><i class="fa fa-check"></i><b>A.6</b> Shoe Outsole Impression Evidence</a></li>
<li class="chapter" data-level="A.7" data-path="glossary.html"><a href="glossary.html#trace-glass-evidence"><i class="fa fa-check"></i><b>A.7</b> Trace Glass Evidence</a></li>
<li class="chapter" data-level="A.8" data-path="glossary.html"><a href="glossary.html#decision-making-in-forensic-identification-tasks"><i class="fa fa-check"></i><b>A.8</b> Decision-making in Forensic Identification Tasks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Open Forensic Science in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="glass" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Trace glass evidence: chemical composition</h1>
<div id="soyoung-park-sam-tyner-1" class="section level4 unnumbered">
<h4><em>Soyoung Park, Sam Tyner</em></h4>
<p><img src="img/brokenglass.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="introduction-5" class="section level2">
<h2><span class="header-section-number">7.1</span> Introduction</h2>
<p>It is easy to imagine a crime scene with glass fragments: a burglar may have broken a glass door, a glass bottle could have been used in an assault, or a domestic disturbance may involve throwing something through a window. During the commission of a crime, there are many ways that glass can break and be transferred from the scene. The study of glass fragments is important to forensic science because the glass broken at the scene can transfer to the perpetrator’s shoes, clothing, or even their hair <span class="citation">(Curran, Hicks, and Buckleton <a href="#ref-curranbook">2000</a>)</span>.</p>
<p>Crime scene investigators collect fragments of glass at the scene as a part of the evidence collection process, and the fragments are sent to the forensic science lab for processing. Similarly, evidence such as clothing and shoes are collected from a suspect, and if glass is found, the fragments are sent to the lab and compared to the fragments found at the scene. The question that the analyst usually tries to answer is, “Did these glass fragments come from the same source?” This is a <em>source level</em> question, meaning that the comparison of the fragments will only tell the investigators whether or not the fragments from the suspect and the fragments from the scene have the same origin. As discussed in Section <a href="intro.html#forscip">1.3</a>, the forensic analysis will not inform investigators <em>how</em> the suspect came into contact (<em>activity level</em>) with the glass or if the suspect was the perpetrator of the crime (<em>offense level</em>) <span class="citation">(Roger Cook et al. <a href="#ref-hop">1998</a>)</span>.</p>
<div id="problems-of-interest" class="section level3">
<h3><span class="header-section-number">7.1.1</span> Problems of interest</h3>
<p>There are two key problems of interest in glass fragments comparison, but before defining them, we need to define the different glass involved in the investigation of a crime. Glass fragments found on the suspect, for example in their hair, shoes, or clothes, are <a href="glossary.html#def:questioned"><em>questioned</em></a> fragments, which we denote by <span class="math inline">\(Q\)</span>. Glass fragments found at the crime scene, for example in front of a broken window or taken from the broken window, are <a href="glossary.html#def:known"><em>known</em></a> fragments, which we denote <span class="math inline">\(K\)</span>. This brings us to a <a href="glossary.html#def:specsource">specific source</a> question: Did the questioned fragments <span class="math inline">\(Q\)</span> found on the suspect come from the same source of glass as the known fragments <span class="math inline">\(K\)</span>, which we know belong to a specific piece of glass at the scene? The goal is now to quantify the similarity between <span class="math inline">\(Q\)</span> and <span class="math inline">\(K\)</span>. There are lots of ways measure similarity between two glass fragments, but the metric should be defined according to available databases of glass fragment measurements for which ground truth is known. For example, if we have elemental compositions measured in parts per million (ppm) as numerical values, the similarity can be quantified by the difference of the chemical compositions of <span class="math inline">\(Q\)</span> and <span class="math inline">\(K\)</span>.</p>
</div>
<div id="current-practice-1" class="section level3">
<h3><span class="header-section-number">7.1.2</span> Current practice</h3>
<p>There are many types of glass measurements such as color, thickness, <a href="glossary.html#def:ri">refractive index</a> (RI) and chemical concentrations. In this chapter, we will focus on <a href="glossary.html#def:floatglass">float glass</a> that is most frequently used in windows, doors and automobiles. For discussions of the other measurements see e.g. <span class="citation">Curran, Hicks, and Buckleton (<a href="#ref-curranbook">2000</a>)</span>. The elemental concentrations of float glass that we use here were obtained through inductively coupled mass spectrometry with a laser add-on (LA-ICP-MS). In the current practice, there are two analysis guides from <a href="#def:ASTM">ASTM International</a>, <span class="citation">(ASTM-E2330-12 <a href="#ref-ASTME233012">2012</a>)</span> and <span class="citation">(ASTM-E2927-16 <a href="#ref-ASTME292716">2016</a>)</span>. To determine the source of glass fragments according to these two guides, intervals around the mean concentrations are computed for each element, and if all elements’ intervals overlap, then the conclusion is that the fragments come from the same source. For more detail on these methods, see <span class="citation">ASTM-E2330-12 (<a href="#ref-ASTME233012">2012</a>)</span> and <span class="citation">ASTM-E2927-16 (<a href="#ref-ASTME292716">2016</a>)</span>.</p>
</div>
<div id="comparing-glass-fragments" class="section level3">
<h3><span class="header-section-number">7.1.3</span> Comparing glass fragments</h3>
<p>In order to determine if two glass fragments come from the same source, a forensic analyst considers many properties of the glass, including color, <a href="glossary.html#def:fluor">fluorescence</a>, thickness, surface features, curvature, and chemical composition. All methods for examining these properties, except for methods of chemical composition analysis, are non-destructive. If the fragments are large, exclusion are easy to reach if the glass are of different colors because of the wide variety of glass colors possible in manufacturing. Typically, however, glass fragments are quite small and color determination is very difficult. Similarly, thickness of glass is dictated by the manufacturing process, which aims for uniform thickness, so if two glass fragments differ in thickness by more than 0.25mm, an exclusion is made <span class="citation">(Bottrell <a href="#ref-glassbackground">2009</a>)</span>. For glass fragments of the same color and thickness, microscopic techniques for determining light absorption (fluorescence), curvature, surface features (such as coatings), are used before the destructive chemical composition analysis.</p>
</div>
<div id="goal-of-this-chapter-1" class="section level3">
<h3><span class="header-section-number">7.1.4</span> Goal of this chapter</h3>
<p>In this chapter, we construct a new rule for making glass source conclusions using the <a href="glossary.html#def:rfdef">random forest</a> algorithm to classify the source of glass fragments <span class="citation">(Park and Carriquiry <a href="#ref-park2018">2019</a><a href="#ref-park2018">a</a>)</span>.</p>
</div>
</div>
<div id="data-5" class="section level2">
<h2><span class="header-section-number">7.2</span> Data</h2>
<div id="chemical-composition-of-glass" class="section level3">
<h3><span class="header-section-number">7.2.1</span> Chemical composition of glass</h3>
<p>The process for determining the chemical composition of a glass fragment is given in great detail in <span class="citation">ASTM-E2330-12 (<a href="#ref-ASTME233012">2012</a>)</span> and <span class="citation">ASTM-E2927-16 (<a href="#ref-ASTME292716">2016</a>)</span>. This destructive method determines elemental composition with Inductively Coupled Plasma Mass Spectrometry (ICP-MS). Up to 40 elements can be detected in a glass fragment using this method. In <span class="citation">Weis et al. (<a href="#ref-weisglass">2011</a>)</span>, only 18 elements are used: calcium (Ca), sodium (NA) and magnesium (Mg) are the major elements, followed by aluminum (Al), potassium (K) and iron (Fe) as minor elements, and lithium (Li), titanium (Ti), manganese (Mn), rubidium (Rb), strontium (Sr), zirconium (Zr), barium (Ba), lanthanum (La), cerium (Ce), neodymium (Nd), hafnium (Hf), and lead (Pb) as the trace elements. The methods of <span class="citation">Weis et al. (<a href="#ref-weisglass">2011</a>)</span> use standard deviations (<span class="math inline">\(\sigma\)</span>) of repeated measurements of the same fragment to create intervals around the measurements. Intervals of width <span class="math inline">\(2\sigma, 4\sigma, 6\sigma, 8\sigma, 10\sigma, 12\sigma, 16\sigma, 20\sigma, 30\sigma,\)</span> and <span class="math inline">\(40\sigma\)</span> are considered for overlap.</p>
</div>
<div id="data-source" class="section level3">
<h3><span class="header-section-number">7.2.2</span> Data source</h3>
<p>Dr. Alicia Carriquiry of Iowa State University commissioned the collection of a large database of chemical compositions of float glass samples. The details of this database are explained in <span class="citation">Park and Carriquiry (<a href="#ref-park2018">2019</a><a href="#ref-park2018">a</a>)</span>. The full database is available <a href="https://github.com/CSAFE-ISU/AOAS-2018-glass-manuscript/tree/master/glassdata">here</a>. The database includes 31 panes of float glass manufactured by Company A and 17 panes manufactured by Company B, both located in the United States. The Company A panes are labeled AA, AB, … , AAR, and the Company B panes are labeled BA, BB, … ,BR. The panes from Company A were produced during a three week period (January 3-24, 2017) and the panes from Company B were produced during a two week period (December 5-16, 2016).</p>
<!-- You don't talk about the ribbon before now so people won't know what you're talking about. Either explain it or find another way to talk about variability without mentioning the ribbon. -->
<p>To understand variability within a ribbon of glass, two glass panes were collected on almost all days in each company, one from the left side and one from the right side of the ribbon. Twenty four fragments were randomly sampled from each glass pane. Five replicate measurements were obtained for 21 of the 24 fragments in each pane; for the remaining three fragments in each pane, we obtained 20 replicate measurements. Therefore, each pane has 165 measurements for 18 elements. For example, see the heuristic in Figure <a href="glass.html#fig:fragsample">7.1</a>. In some panes, there may be a fragment with fewer than five replicate measurements. The unit for all measurements is parts per million (ppm).</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
pane &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(<span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">16</span>, <span class="dt">y =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)
n &lt;-<span class="st"> </span><span class="kw">nrow</span>(pane)
pane<span class="op">$</span>id &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span>n
frags &lt;-<span class="st"> </span><span class="kw">sample</span>(n, <span class="dv">24</span>)
rep20 &lt;-<span class="st"> </span><span class="kw">sample</span>(frags, <span class="dv">3</span>)
rep5 &lt;-<span class="st"> </span>frags[<span class="op">!</span>(frags <span class="op">%in%</span><span class="st"> </span>rep20)]
pane_sample &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">frag =</span> <span class="kw">c</span>(<span class="kw">rep</span>(rep5, <span class="dt">each =</span> <span class="dv">5</span>), <span class="kw">rep</span>(rep20, <span class="dt">each =</span> <span class="dv">20</span>)), 
    <span class="dt">rep =</span> <span class="kw">c</span>(<span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>, <span class="dv">21</span>), <span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>, <span class="dv">3</span>)))
sample_data &lt;-<span class="st"> </span><span class="kw">left_join</span>(pane, pane_sample, <span class="dt">by =</span> <span class="kw">c</span>(<span class="dt">id =</span> <span class="st">&quot;frag&quot;</span>))
<span class="kw">ggplot</span>(<span class="dt">data =</span> sample_data, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_tile</span>(<span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_jitter</span>(<span class="kw">aes</span>(<span class="dt">color =</span> <span class="kw">as.factor</span>(rep)), <span class="dt">alpha =</span> <span class="fl">0.8</span>, <span class="dt">size =</span> <span class="fl">0.5</span>) <span class="op">+</span><span class="st"> </span><span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;black&quot;</span>, 
    <span class="dv">20</span>))) <span class="op">+</span><span class="st"> </span><span class="kw">theme_void</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;none&quot;</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:fragsample"></span>
<img src="open-forensic-science-in-r_files/figure-html/fragsample-1.png" alt="An example of how the glass fragments were sampled, if the 64 squares are imagined to be randomly broken fragments within a pane." width="672" />
<p class="caption">
Figure 7.1: An example of how the glass fragments were sampled, if the 64 squares are imagined to be randomly broken fragments within a pane.
</p>
</div>
</div>
<div id="data-structure" class="section level3">
<h3><span class="header-section-number">7.2.3</span> Data structure</h3>
<p>Next, we look at the glass data.</p>
<pre class="sourceCode r"><code class="sourceCode r">glass &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;dat/glass_raw_all.csv&quot;</span>)
<span class="kw">head</span>(glass)</code></pre>
<pre><code>##   pane fragment Rep mfr element       ppm
## 1   AA        1   1   A      Al  2678.000
## 2   AA        1   1   A      Ba    10.800
## 3   AA        1   1   A      Ca 63140.000
## 4   AA        1   1   A      Ce     9.520
## 5   AA        1   1   A      Fe   667.000
## 6   AA        1   1   A      Hf     1.148</code></pre>
<p>The elements have very different scales, as some (e.g. Ca) are major elements, some (e.g. Al) are minor elements, and others (e.g Hf) are trace elements. Thus, we take the natural log transformation of all measurements to put them on a similar scale.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># need to make sure the panes are shown in order of mfr date</span>
pane_order &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">paste0</span>(<span class="st">&quot;A&quot;</span>, LETTERS[<span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">13</span>, <span class="dv">15</span>, <span class="dv">22</span><span class="op">:</span><span class="dv">25</span>)]), <span class="kw">paste0</span>(<span class="st">&quot;AA&quot;</span>, LETTERS[<span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, 
    <span class="dv">6</span>, <span class="dv">8</span><span class="op">:</span><span class="dv">13</span>, <span class="dv">17</span><span class="op">:</span><span class="dv">18</span>)]), <span class="kw">names</span>(<span class="kw">table</span>(glass<span class="op">$</span>pane))[<span class="kw">c</span>(<span class="dv">32</span><span class="op">:</span><span class="dv">48</span>)])
glass<span class="op">$</span>pane &lt;-<span class="st"> </span><span class="kw">ordered</span>(glass<span class="op">$</span>pane, <span class="dt">levels =</span> pane_order)

glass_log &lt;-<span class="st"> </span>glass <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">log_ppm =</span> <span class="kw">log</span>(ppm))
glass_log <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span>ppm) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">spread</span>(element, log_ppm) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(mfr, pane, 
    fragment, Rep, Li, Na, Mg, Al, K, Ca) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre>
<pre><code>##   mfr pane fragment Rep        Li       Na       Mg       Al        K
## 1   A   AA        1   1 0.8329091 11.54025 10.04715 7.892826 7.136483
## 2   A   AA        1   2 0.5423243 11.53772 10.03671 7.883069 7.126248
## 3   A   AA        1   3 0.7227060 11.53126 10.04499 7.909122 7.127694
## 4   A   AA        1   4 0.7975072 11.54219 10.05449 7.912423 7.144407
## 5   A   AA        1   5 0.7227060 11.52968 10.02260 7.871311 7.103322
## 6   A   AA        2   1 0.5596158 11.52663 10.04107 7.898411 7.118826
##         Ca
## 1 11.05311
## 2 11.04930
## 3 11.04580
## 4 11.06147
## 5 11.01023
## 6 11.03747</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">cols &lt;-<span class="st"> </span>csafethemes<span class="op">:::</span>csafe_cols_secondary[<span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">12</span>)]
glass_log <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(element <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Li&quot;</span>, <span class="st">&quot;Na&quot;</span>, <span class="st">&quot;Mg&quot;</span>, <span class="st">&quot;Al&quot;</span>, <span class="st">&quot;K&quot;</span>, <span class="st">&quot;Ca&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">x =</span> log_ppm, <span class="dt">fill =</span> mfr), <span class="dt">alpha =</span> <span class="fl">0.7</span>) <span class="op">+</span><span class="st"> </span><span class="kw">scale_fill_manual</span>(<span class="dt">name =</span> <span class="st">&quot;Manufacturer&quot;</span>, 
    <span class="dt">values =</span> cols) <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span>element, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="dt">nrow =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Log concentration (ppm)&quot;</span>, 
    <span class="dt">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;top&quot;</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:density"></span>
<img src="open-forensic-science-in-r_files/figure-html/density-1.png" alt="Density estimation of selected chemical compositions, colored by manufacturers" width="672" />
<p class="caption">
Figure 7.2: Density estimation of selected chemical compositions, colored by manufacturers
</p>
</div>
<p>Figure <a href="glass.html#fig:density">7.2</a> shows density plots of six chemical compositions of Al, Ca, K, Li, Mg, Na. Na and Ca (major elements) show density curves from two manufacturers are overlapped, while Al, K show clear separation between curves by manufacturers. This implies that glass fragments from different manufacturers will be very easy to distinguish.</p>
<pre class="sourceCode r"><code class="sourceCode r">glass_log <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(element <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Na&quot;</span>, <span class="st">&quot;Ti&quot;</span>, <span class="st">&quot;Zr&quot;</span>, <span class="st">&quot;Hf&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_boxplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> pane, <span class="dt">y =</span> log_ppm, <span class="dt">fill =</span> mfr), <span class="dt">alpha =</span> <span class="fl">0.8</span>, <span class="dt">outlier.size =</span> <span class="fl">0.5</span>, 
        <span class="dt">size =</span> <span class="fl">0.1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">scale_fill_manual</span>(<span class="dt">name =</span> <span class="st">&quot;Manufacturer&quot;</span>, <span class="dt">values =</span> cols) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">facet_wrap</span>(<span class="op">~</span>element, <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">labeller =</span> label_both) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">scale_x_discrete</span>(<span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;AA&quot;</span>, 
    <span class="kw">rep</span>(<span class="st">&quot;&quot;</span>, <span class="dv">30</span>), <span class="st">&quot;BA&quot;</span>, <span class="kw">rep</span>(<span class="st">&quot;&quot;</span>, <span class="dv">15</span>), <span class="st">&quot;BR&quot;</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Pane (in order of manufacture)&quot;</span>, 
    <span class="dt">y =</span> <span class="st">&quot;Log concentration (ppm)&quot;</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:boxplot"></span>
<img src="open-forensic-science-in-r_files/figure-html/boxplot-1.png" alt="Box plot of four elements in 48 panes, ordered by date of production, from two manufacturers." width="100%" />
<p class="caption">
Figure 7.3: Box plot of four elements in 48 panes, ordered by date of production, from two manufacturers.
</p>
</div>
<p>Figure @ref(fig:box plot) shows box plots of the measurements of four elements (Na, Ti, Zr, Hf) in each of the 48 panes in the database, colored by manufacturer. Boxes are ordered by date of production within manufacturer. We can confirm the between- and within- pane variability. Interestingly, element values of Zr and Hf in manufacturer A are both decreasing in time, which is evidence that the element measurements are highly correlated. To account for this relationship, we use methods that do not require independence of measurements.</p>
<pre class="sourceCode r"><code class="sourceCode r">col_data_AA &lt;-<span class="st"> </span>glass_log_long[, <span class="dv">-6</span>] <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(pane <span class="op">==</span><span class="st"> &quot;AA&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">spread</span>(element, 
    log_ppm) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(fragment) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise_if</span>(is.numeric, mean, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)

col_data_BA &lt;-<span class="st"> </span>glass_log_long[, <span class="dv">-6</span>] <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(pane <span class="op">==</span><span class="st"> &quot;BA&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">spread</span>(element, 
    log_ppm) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(fragment) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise_if</span>(is.numeric, mean, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)

P1 &lt;-<span class="st"> </span><span class="kw">ggcorr</span>(col_data_AA[, <span class="dv">3</span><span class="op">:</span><span class="dv">20</span>], <span class="dt">geom =</span> <span class="st">&quot;blank&quot;</span>, <span class="dt">label =</span> <span class="ot">TRUE</span>, <span class="dt">hjust =</span> <span class="fl">0.75</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">10</span>, <span class="kw">aes</span>(<span class="dt">color =</span> coefficient <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="dt">alpha =</span> <span class="kw">abs</span>(coefficient) <span class="op">&gt;</span><span class="st"> </span>
<span class="st">        </span><span class="fl">0.5</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">scale_alpha_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">`</span><span class="dt">TRUE</span><span class="st">`</span> =<span class="st"> </span><span class="fl">0.25</span>, <span class="st">`</span><span class="dt">FALSE</span><span class="st">`</span> =<span class="st"> </span><span class="dv">0</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">guides</span>(<span class="dt">color =</span> <span class="ot">FALSE</span>, <span class="dt">alpha =</span> <span class="ot">FALSE</span>)

P2 &lt;-<span class="st"> </span><span class="kw">ggcorr</span>(col_data_BA[, <span class="dv">3</span><span class="op">:</span><span class="dv">20</span>], <span class="dt">geom =</span> <span class="st">&quot;blank&quot;</span>, <span class="dt">label =</span> <span class="ot">TRUE</span>, <span class="dt">hjust =</span> <span class="fl">0.75</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">10</span>, <span class="kw">aes</span>(<span class="dt">color =</span> coefficient <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="dt">alpha =</span> <span class="kw">abs</span>(coefficient) <span class="op">&gt;</span><span class="st"> </span>
<span class="st">        </span><span class="fl">0.5</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">scale_alpha_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">`</span><span class="dt">TRUE</span><span class="st">`</span> =<span class="st"> </span><span class="fl">0.25</span>, <span class="st">`</span><span class="dt">FALSE</span><span class="st">`</span> =<span class="st"> </span><span class="dv">0</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">guides</span>(<span class="dt">color =</span> <span class="ot">FALSE</span>, <span class="dt">alpha =</span> <span class="ot">FALSE</span>)

P1 <span class="op">+</span><span class="st"> </span>P2</code></pre>
<!-- 
Figure \@ref(fig:correlation) shows correlation plot of pane AA and pane BA. When there is +1 correlation, then there is a strong positive correlation between two variables and when there is -1 correlation, then there is a strong negative correlation. In each correlation plot, we colored blue and red when there is correlation larger than 0.5 or lower than -0.5. In both correlation plots, we see many blue and red areas, so that there are some dependencies among chemical compositions in glass fragments measurements.  
-->
</div>
</div>
<div id="glass_rpkgs" class="section level2">
<h2><span class="header-section-number">7.3</span> R Packages</h2>
<p>We propose a <a href="glossary.html#def:ml">machine learning</a> method to quantify the similarity between two glass fragments <span class="math inline">\(Q\)</span> and <span class="math inline">\(K\)</span>. The goal here is to construct a <a href="glossary.html#def:classifier">classifier</a> that predicts, with low error, whether or not <span class="math inline">\(Q\)</span> and <span class="math inline">\(K\)</span> have the same source. Using the glass database, we construct many pairwise comparisons between two glass fragments with known sources, and we will record their source as either same source or different source.</p>
<p>To construct the set of comparisons, we</p>
<ol style="list-style-type: decimal">
<li>Take the natural log of all measurements of all glass fragments. (ppm to <span class="math inline">\(\log\)</span>(ppm))</li>
<li>Select one pane of glass in the database to be the “questioned” source. Sample one fragment from this pane, and call it <span class="math inline">\(Q\)</span>.</li>
<li>Select one pane of glass in the database to be the “known” source. Sample one fragment from this pane, and call it <span class="math inline">\(K\)</span>.</li>
<li>Construct the response variable: if the panes in 2 and 3 are the same, the response variable is KM for known mates. Otherwise, the response variable is KNM for known non-mates.</li>
<li>Construct the features: take the mean of the repeated measurements of <span class="math inline">\(Q\)</span> and <span class="math inline">\(K\)</span> in each element, and take the absolute value of the difference between the mean of <span class="math inline">\(Q\)</span> and the mean of <span class="math inline">\(K\)</span>.</li>
<li>Repeat 2-5 until we have a data set suitable for training a classifier.</li>
</ol>
<!--caret package to fit the data to random forest on cross-validation-->
<p>We use the R package <a href="https://topepo.github.io/caret/index.html"><code>caret</code></a> to train a random forest classifier to determine whether two glass fragments (<span class="math inline">\(Q\)</span> and <span class="math inline">\(K\)</span>) have the same source or have different sources <span class="citation">(Jed Wing et al. <a href="#ref-R-caret">2018</a>)</span>.</p>
<p>To begin, the package can be installed from CRAN:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;caret&quot;</span>)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(caret)
<span class="co"># other package used for plotting</span>
<span class="kw">library</span>(GGally)
<span class="kw">library</span>(patchwork)</code></pre>
<p>The R package <code>caret</code> (<strong>C</strong>lassification <strong>A</strong>nd <strong>RE</strong>gression <strong>T</strong>raining) is used for applied predictive modeling. The <code>caret</code> package allows us to run 238 different models as well as adjusting data splitting, preprocessing, feature selection, tuning parameter, and variable importance estimation. We use it here for fitting a random forest model to our data using cross-validation and down-sampling.</p>
<!--Histogram of Mates and Non-mates -->
<pre class="sourceCode r"><code class="sourceCode r">diff_Q_K_data &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;dat/rf_data_kfrags_1z.rds&quot;</span>)</code></pre>
<table>
<caption>
<span id="tab:diffdata2">Table 7.1: </span>Differences of log values of concentrations (Li, Na, Mg, Al, K, Ca) from pairs of known mates (KM) and known non-mates (KNM)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Class
</th>
<th style="text-align:right;">
Li
</th>
<th style="text-align:right;">
Na
</th>
<th style="text-align:right;">
Mg
</th>
<th style="text-align:right;">
Al
</th>
<th style="text-align:right;">
K
</th>
<th style="text-align:right;">
Ca
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
KM
</td>
<td style="text-align:right;">
0.0078
</td>
<td style="text-align:right;">
0.0043
</td>
<td style="text-align:right;">
0.0089
</td>
<td style="text-align:right;">
0.0270
</td>
<td style="text-align:right;">
0.0103
</td>
<td style="text-align:right;">
0.0149
</td>
</tr>
<tr>
<td style="text-align:left;">
KM
</td>
<td style="text-align:right;">
0.0845
</td>
<td style="text-align:right;">
0.0065
</td>
<td style="text-align:right;">
0.0042
</td>
<td style="text-align:right;">
0.0049
</td>
<td style="text-align:right;">
0.0126
</td>
<td style="text-align:right;">
0.0032
</td>
</tr>
<tr>
<td style="text-align:left;">
KM
</td>
<td style="text-align:right;">
0.0826
</td>
<td style="text-align:right;">
0.0170
</td>
<td style="text-align:right;">
0.0069
</td>
<td style="text-align:right;">
0.0137
</td>
<td style="text-align:right;">
0.0259
</td>
<td style="text-align:right;">
0.0014
</td>
</tr>
<tr>
<td style="text-align:left;">
KNM
</td>
<td style="text-align:right;">
0.5362
</td>
<td style="text-align:right;">
0.0581
</td>
<td style="text-align:right;">
0.0267
</td>
<td style="text-align:right;">
0.0741
</td>
<td style="text-align:right;">
0.0834
</td>
<td style="text-align:right;">
0.0619
</td>
</tr>
<tr>
<td style="text-align:left;">
KNM
</td>
<td style="text-align:right;">
0.2437
</td>
<td style="text-align:right;">
0.0283
</td>
<td style="text-align:right;">
0.0092
</td>
<td style="text-align:right;">
0.0181
</td>
<td style="text-align:right;">
0.0377
</td>
<td style="text-align:right;">
0.0386
</td>
</tr>
<tr>
<td style="text-align:left;">
KNM
</td>
<td style="text-align:right;">
0.2319
</td>
<td style="text-align:right;">
0.0316
</td>
<td style="text-align:right;">
0.0283
</td>
<td style="text-align:right;">
0.0001
</td>
<td style="text-align:right;">
0.0437
</td>
<td style="text-align:right;">
0.0518
</td>
</tr>
</tbody>
</table>
<p>Table <a href="glass.html#tab:diffdata2">7.1</a> shows the example of pairwise differences among glass measurements. If we take the difference of two fragments from the same pane, then KM is assigned to the response variable of <code>Class</code>. If we take the difference of two fragments from two different panes, then KNM is assigned to variable <code>Class</code>. Each row has 18 differences and one variable <code>Class</code> indicating the source of two glass fragments. By taking pairwise differences, there are many more KNM pairs than KM pairs: we can construct 67,680 KNM pairs but only 1,440 KM pairs from the glass database.</p>
<!--head of difference data  -->
<pre class="sourceCode r"><code class="sourceCode r">diff_Q_K_data <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">gather</span>(element, diff, Li<span class="op">:</span>Pb) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(element <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Zr&quot;</span>, 
    <span class="st">&quot;Li&quot;</span>, <span class="st">&quot;Hf&quot;</span>, <span class="st">&quot;Ca&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">x =</span> diff, <span class="dt">fill =</span> class), 
    <span class="dt">alpha =</span> <span class="fl">0.7</span>) <span class="op">+</span><span class="st"> </span><span class="kw">scale_fill_manual</span>(<span class="dt">name =</span> <span class="st">&quot;Class&quot;</span>, <span class="dt">values =</span> cols) <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span>element, 
    <span class="dt">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="dt">nrow =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Difference between Q and K (log(ppm))&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;top&quot;</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:diffhist"></span>
<img src="open-forensic-science-in-r_files/figure-html/diffhist-1.png" alt="Histogram of differences from four chemical elements among KM and KNM." width="672" />
<p class="caption">
Figure 7.4: Histogram of differences from four chemical elements among KM and KNM.
</p>
</div>
<p>Figure <a href="glass.html#fig:diffhist">7.4</a> shows the distribution of differences for KM and KNM pairs in the Ca, Hf, Li, and Zr. Across all elements, distribution of differences from KNM pairs are more dispersed than differences of KM. The differences of KM have high density near zero, while the KNM measurements are shifted to the right and have a long tail. These differences for all 18 elements will be the <a href="glossary.html#def:features">features</a> of the random forest.</p>
<!--random forest classifier / train data and test data separation -->
<p>Finally, we construct the random forest classifier. Since the data have 1,440 KM and 67,680 KNM observations, the response variable is imbalanced. With this large imbalance, the algorithm can simply predict KNM and have low error rate without learning anything about the properties of the KM class. You can find more ways to consider this imbalance problem for fitting the random forest in this glass fragment source prediction in <span class="citation">(Park and Carriquiry <a href="#ref-park2018">2019</a><a href="#ref-park2018">a</a>)</span>. In this chapter, we will down-sample the KNM observations to equal the number of KM observations. That way, we will have 1,440 KM and 1,440 KNM comparisons. Then, we sample 70% of them to be the training set and the remaining 30% are the testing set.</p>
<pre class="sourceCode r"><code class="sourceCode r">diff_Q_K_data<span class="op">$</span>class &lt;-<span class="st"> </span><span class="kw">as.factor</span>(diff_Q_K_data<span class="op">$</span>class)
<span class="co"># Down sample the majority class to the same number of minority class</span>
<span class="kw">set.seed</span>(<span class="dv">123789</span>)
down_diff_Q_K_data &lt;-<span class="st"> </span><span class="kw">downSample</span>(diff_Q_K_data[, <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">18</span>)], diff_Q_K_data<span class="op">$</span>class)
down_diff_Q_K_data &lt;-<span class="st"> </span>down_diff_Q_K_data <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">id =</span> <span class="kw">row_number</span>())
<span class="kw">names</span>(down_diff_Q_K_data)[<span class="dv">19</span>] &lt;-<span class="st"> &quot;class&quot;</span>
<span class="kw">table</span>(down_diff_Q_K_data<span class="op">$</span>class)</code></pre>
<pre><code>## 
##   KM  KNM 
## 1440 1440</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Create training set</span>
train_data &lt;-<span class="st"> </span>down_diff_Q_K_data <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">sample_frac</span>(<span class="fl">0.7</span>)
<span class="co"># Create test set</span>
test_data &lt;-<span class="st"> </span><span class="kw">anti_join</span>(down_diff_Q_K_data, train_data, <span class="dt">by =</span> <span class="st">&quot;id&quot;</span>)
train_data &lt;-<span class="st"> </span>train_data[, <span class="dv">-20</span>]  <span class="co">#exclude id </span>
test_data &lt;-<span class="st"> </span>test_data[, <span class="dv">-20</span>]  <span class="co">#exclude id </span>
<span class="co"># dim(train_data) # 2016 19 dim(test_data) # 864 19</span></code></pre>
<!--We down-sampled the majority class of KNM into the same number of minority class of KM. In the end, we have 1,440 KM and 1,440 KNM pairs of comparisons as our data. After then, we randomly selected 70% of them as training set for fitting the random forest classifier and set aside the rest of 30% data as test data for the validation of the performance.-->
<p>After down-sampling and setting aside 30% of the data for testing, we can train the classifier. Below is the R code to fit the random forest, using <code>caret</code> <span class="citation">(Jed Wing et al. <a href="#ref-R-caret">2018</a>)</span>. The tuning parameter for the random forest algorithm is <code>mtry</code>, the number of variables available for splitting at each tree node. We use five values (1, 2, 3, 4, 5) to tune <code>mtry</code> and pick the optimal one. For the classification, the default <code>mtry</code> is the square root of the number of predictor variables (it is <span class="math inline">\(\sqrt{18} \approx 4.2\)</span>, in our study). To pick the optimal <code>mtry</code> parameter, the area under the <a href="glossary.html#def:roc">receiver operating characteristic</a> (ROC) curve is calculated. The optimal value will result the highest area under the ROC curve (AUC). The data are also automatically centered and scaled for each predictor. We use 10-fold <a href="glossary.html#def:crossval">cross-valildation</a> to evaluate the random forest algorithm and repeat entire process three times.</p>
<pre class="sourceCode r"><code class="sourceCode r">ctrl &lt;-<span class="st"> </span><span class="kw">trainControl</span>(<span class="dt">method =</span> <span class="st">&quot;repeatedcv&quot;</span>, <span class="dt">number =</span> <span class="dv">10</span>, <span class="dt">repeats =</span> <span class="dv">3</span>, <span class="dt">savePredictions =</span> <span class="st">&quot;final&quot;</span>, 
    <span class="dt">summaryFunction =</span> twoClassSummary, <span class="dt">classProbs =</span> <span class="ot">TRUE</span>)

<span class="co"># mtry is recommended to use sqrt(# of variables)=sqrt(18) so 1:5 are tried</span>
<span class="co"># to find the optimal one</span>
RF_classifier &lt;-<span class="st"> </span><span class="kw">train</span>(class <span class="op">~</span><span class="st"> </span>., train_data, <span class="dt">method =</span> <span class="st">&quot;rf&quot;</span>, <span class="dt">tuneGrid =</span> <span class="kw">expand.grid</span>(<span class="dt">.mtry =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>)), 
    <span class="dt">metric =</span> <span class="st">&quot;ROC&quot;</span>, <span class="dt">preProc =</span> <span class="kw">c</span>(<span class="st">&quot;center&quot;</span>, <span class="st">&quot;scale&quot;</span>), <span class="dt">trControl =</span> ctrl)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">RF_classifier &lt;-<span class="st"> </span><span class="kw">readRDS</span>(<span class="st">&quot;dat/RF_classifier.RDS&quot;</span>)
RF_classifier</code></pre>
<pre><code>## Random Forest 
## 
## 2016 samples
##   18 predictor
##    2 classes: &#39;KM&#39;, &#39;KNM&#39; 
## 
## Pre-processing: centered (18), scaled (18) 
## Resampling: Cross-Validated (10 fold, repeated 3 times) 
## Summary of sample sizes: 1815, 1814, 1814, 1814, 1815, 1814, ... 
## Resampling results across tuning parameters:
## 
##   mtry  ROC        Sens       Spec     
##   1     0.9637918  0.9826797  0.8323266
##   2     0.9641196  0.9807190  0.8467239
##   3     0.9625203  0.9758170  0.8457239
##   4     0.9624018  0.9738562  0.8467172
##   5     0.9614865  0.9728758  0.8473838
## 
## ROC was used to select the optimal model using the largest value.
## The final value used for the model was mtry = 2.</code></pre>
<p>From the RF fitting result, it showed the AUC (ROC), Sens (<a href="glossary.html#def:sensitivity">Sensitivity</a>) and Spec (<a href="glossary.html#def:specificity">Specificity</a>) values in each mtry values. R-package caret selects the best mtry value (it is 2, in our study) to give the highest AUC (ROC) value 0.964, from 10-fold cross-validation and 3 repeated process.</p>
<p>The final performance of the random forest algorithm with the optimal mtry of 2 with 500 of number of trees. In the training set, the false negative rate is 0.02 and the false positive rate is 0.153 of false positive rate, which is the optimized classification result. We see the OOB estimate of error rate of 0.085, which is the average error rate from the fold left out of the training set during cross-validation.</p>
<pre class="sourceCode r"><code class="sourceCode r">RF_classifier<span class="op">$</span>finalModel<span class="op">$</span>confusion</code></pre>
<pre><code>##       KM KNM class.error
## KM  1000  20  0.01960784
## KNM  152 844  0.15261044</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">imp &lt;-<span class="st"> </span><span class="kw">varImp</span>(RF_classifier)<span class="op">$</span>importance
imp &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(imp)
imp<span class="op">$</span>varnames &lt;-<span class="st"> </span><span class="kw">rownames</span>(imp)  <span class="co"># row names to column</span>
<span class="kw">rownames</span>(imp) &lt;-<span class="st"> </span><span class="ot">NULL</span>
imp &lt;-<span class="st"> </span>imp <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(<span class="op">-</span>Overall)
imp<span class="op">$</span>varnames &lt;-<span class="st"> </span><span class="kw">as.character</span>(imp<span class="op">$</span>varnames)
elements &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;dat/elements.csv&quot;</span>)

imp <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">left_join</span>(elements[, <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>)], <span class="dt">by =</span> <span class="kw">c</span>(<span class="dt">varnames =</span> <span class="st">&quot;symb&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(varnames, 
    Overall), <span class="dt">y =</span> Overall, <span class="dt">fill =</span> classification)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, 
    <span class="dt">color =</span> <span class="st">&quot;grey40&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">scale_fill_brewer</span>(<span class="dt">name =</span> <span class="st">&quot;Element&quot;</span>, <span class="dt">palette =</span> <span class="st">&quot;Blues&quot;</span>, 
    <span class="dt">direction =</span> <span class="dv">-1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;Overall importance&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Variable&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">scale_y_continuous</span>(<span class="dt">position =</span> <span class="st">&quot;right&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">coord_flip</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</code></pre>
<div class="figure" style="text-align: center"><span id="fig:varimp"></span>
<img src="open-forensic-science-in-r_files/figure-html/varimp-1.png" alt="Variable importance from the RF classifier, colored by element types (major, minor or trace)." width="75%" />
<p class="caption">
Figure 7.5: Variable importance from the RF classifier, colored by element types (major, minor or trace).
</p>
</div>
<p>By fitting the random forest algorithm, we can also get a measure of variable importance. This metric ranks which elements out of 18 are most important to correctly predicting the source of the glass fragments. Figure <a href="glass.html#fig:varimp">7.5</a> shows that elements K, Ce, Zr, Rb, and Hf are five very important variables and Pb, Sr, Na, Ca, and Mg are five minimally important variables. All major elements are not important: this is not surprising because all glass is, broadly speaking, very similar chemically. Conversely, most of the trace elements are ranked in the top half.</p>
</div>
<div id="drawing-conclusions-4" class="section level2">
<h2><span class="header-section-number">7.4</span> Drawing Conclusions</h2>
<p>The result of the random forest classifier is a probability of the observation belonging to the two classes, KM and KNM, and a predicted class. For an observation, if the class probability for KM is greater than 0.5, then the class prediction is M (mated), otherwise it is NM (non-mated). We use the random forest classifier to predict on the test set. <!--If the random forest predicts the two fragments come from the same pane, we denote this with M for mated. If it predicts they come from different panes, we denote this with NM for non-mated.--> Recall that we know the ground truth, KM and KNM for the test data.</p>
<!-- show density estimation of RF score in testing set -->
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Get prediction from RF classifier in test data</span>
pred_class &lt;-<span class="st"> </span><span class="kw">predict</span>(RF_classifier, test_data)
table_pred_class &lt;-<span class="st"> </span><span class="kw">confusionMatrix</span>(pred_class, test_data<span class="op">$</span>class)<span class="op">$</span>table
table2 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(table_pred_class) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">spread</span>(Reference, Freq)
table2<span class="op">$</span>Prediction &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;M&quot;</span>, <span class="st">&quot;NM&quot;</span>)
table2 <span class="op">%&gt;%</span><span class="st"> </span>knitr<span class="op">::</span><span class="kw">kable</span>(<span class="dt">format =</span> <span class="st">&quot;html&quot;</span>, <span class="dt">caption =</span> <span class="st">&quot;Classification result of test set&quot;</span>, 
    <span class="dt">longtable =</span> <span class="ot">FALSE</span>, <span class="dt">row.names =</span> <span class="ot">FALSE</span>)</code></pre>
<table>
<caption>
<span id="tab:testtable">Table 7.2: </span>Classification result of test set
</caption>
<thead>
<tr>
<th style="text-align:left;">
Prediction
</th>
<th style="text-align:right;">
KM
</th>
<th style="text-align:right;">
KNM
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
M
</td>
<td style="text-align:right;">
409
</td>
<td style="text-align:right;">
69
</td>
</tr>
<tr>
<td style="text-align:left;">
NM
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
375
</td>
</tr>
</tbody>
</table>
<p>Table <a href="glass.html#tab:testtable">7.2</a> shows the classification results on the testing set from the random forest. There are 420 KM and 444 KNM comparisons in the test set. For the KM cases, the RF classifier correctly predicts the source as M in 97.4% of cases and wrongly predicts the source as NM in 2.6% of cases. This is the false negative rate, FNR. For the KNM cases, the RF correctly classifies them as NM 84.5% of the time, while 15.5% are incorrectly classified as M. We know that the method resulted in higher FPR (15.5) because the data we have are from many close panes made by the same manufacturer that are difficult to distinguish from one another.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># class probability for the same pane is used as similarity score for RF</span>
prob_prediction &lt;-<span class="st"> </span><span class="kw">predict</span>(RF_classifier, test_data, <span class="dt">type =</span> <span class="st">&quot;prob&quot;</span>)[, <span class="st">&quot;KM&quot;</span>]
test_data<span class="op">$</span>prob &lt;-<span class="st"> </span>prob_prediction

test_data <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">x =</span> prob, <span class="dt">fill =</span> class), <span class="dt">alpha =</span> <span class="fl">0.7</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">scale_fill_manual</span>(<span class="dt">name =</span> <span class="st">&quot;Class&quot;</span>, <span class="dt">values =</span> cols) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Empirical probability for KM from RF classifier&quot;</span>, 
    <span class="dt">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;top&quot;</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:testscore"></span>
<img src="open-forensic-science-in-r_files/figure-html/testscore-1.png" alt="Scores from the RF classifier for the test set. Ground truth (either KM or KNM) is known. Any observations above 0.5 are declared same source, while all others are declared different source. Notice the long tail in the KNM cases." width="672" />
<p class="caption">
Figure 7.6: Scores from the RF classifier for the test set. Ground truth (either KM or KNM) is known. Any observations above 0.5 are declared same source, while all others are declared different source. Notice the long tail in the KNM cases.
</p>
</div>
<!--We draw the empirical class probability of M that is predicted by the random forest classifier for each measurement in test data. -->
<p>Figure <a href="glass.html#fig:testscore">7.6</a> shows the distribution of the RF scores, colored by true classes in test data. The score is the empirical class probability that an observation belongs to the KM class. The modes of the the two classes are well separated, while there is still some overlap between the classes’ density curve. The tail of the distribution of scores for KNMs is more skewed than that of the KMs, which helps explain the higher false positive rate. Table <a href="glass.html#tab:testtable">7.2</a> is the predicted classification result using the cut-off of 0.5. If the RF score is larger than 0.5, then we will predict the pair of glass fragments have the same source (M). If not, then we declare they have different source (NM).</p>
</div>
<div id="case-study-3" class="section level2">
<h2><span class="header-section-number">7.5</span> Case Study</h2>
<p>Here we introduce a new set of five pairs of comparisons and use the random forest classifier we trained in Section @ref(glass_rpkgs) to determine if the two samples being compared are from the same source of glass or from different sources.</p>
<p>Suppose you are given the following data on eight glass samples, where each sample has been measured 5 times:</p>
<div id="htmlwidget-a2bc410551aa8a6e20bb" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-a2bc410551aa8a6e20bb">{"x":{"filter":"none","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156","157","158","159","160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180","181","182","183","184","185","186","187","188","189","190","191","192","193","194","195","196","197","198","199","200","201","202","203","204","205","206","207","208","209","210","211","212","213","214","215","216","217","218","219","220","221","222","223","224","225","226","227","228","229","230","231","232","233","234","235","236","237","238","239","240","241","242","243","244","245","246","247","248","249","250","251","252","253","254","255","256","257","258","259","260","261","262","263","264","265","266","267","268","269","270","271","272","273","274","275","276","277","278","279","280","281","282","283","284","285","286","287","288","289","290","291","292","293","294","295","296","297","298","299","300","301","302","303","304","305","306","307","308","309","310","311","312","313","314","315","316","317","318","319","320","321","322","323","324","325","326","327","328","329","330","331","332","333","334","335","336","337","338","339","340","341","342","343","344","345","346","347","348","349","350","351","352","353","354","355","356","357","358","359","360","361","362","363","364","365","366","367","368","369","370","371","372","373","374","375","376","377","378","379","380","381","382","383","384","385","386","387","388","389","390","391","392","393","394","395","396","397","398","399","400","401","402","403","404","405","406","407","408","409","410","411","412","413","414","415","416","417","418","419","420","421","422","423","424","425","426","427","428","429","430","431","432","433","434","435","436","437","438","439","440","441","442","443","444","445","446","447","448","449","450","451","452","453","454","455","456","457","458","459","460","461","462","463","464","465","466","467","468","469","470","471","472","473","474","475","476","477","478","479","480","481","482","483","484","485","486","487","488","489","490","491","492","493","494","495","496","497","498","499","500","501","502","503","504","505","506","507","508","509","510","511","512","513","514","515","516","517","518","519","520","521","522","523","524","525","526","527","528","529","530","531","532","533","534","535","536","537","538","539","540","541","542","543","544","545","546","547","548","549","550","551","552","553","554","555","556","557","558","559","560","561","562","563","564","565","566","567","568","569","570","571","572","573","574","575","576","577","578","579","580","581","582","583","584","585","586","587","588","589","590","591","592","593","594","595","596","597","598","599","600","601","602","603","604","605","606","607","608","609","610","611","612","613","614","615","616","617","618","619","620","621","622","623","624","625","626","627","628","629","630","631","632","633","634","635","636","637","638","639","640","641","642","643","644","645","646","647","648","649","650","651","652","653","654","655","656","657","658","659","660","661","662","663","664","665","666","667","668","669","670","671","672","673","674","675","676","677","678","679","680","681","682","683","684","685","686","687","688","689","690","691","692","693","694","695","696","697","698","699","700","701","702","703","704","705","706","707","708","709","710","711","712","713","714","715","716","717","718","719","720"],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8],["Al","Al","Al","Al","Al","Ba","Ba","Ba","Ba","Ba","Ca","Ca","Ca","Ca","Ca","Ce","Ce","Ce","Ce","Ce","Fe","Fe","Fe","Fe","Fe","Hf","Hf","Hf","Hf","Hf","K","K","K","K","K","La","La","La","La","La","Li","Li","Li","Li","Li","Mg","Mg","Mg","Mg","Mg","Mn","Mn","Mn","Mn","Mn","Na","Na","Na","Na","Na","Nd","Nd","Nd","Nd","Nd","Pb","Pb","Pb","Pb","Pb","Rb","Rb","Rb","Rb","Rb","Sr","Sr","Sr","Sr","Sr","Ti","Ti","Ti","Ti","Ti","Zr","Zr","Zr","Zr","Zr","Al","Al","Al","Al","Al","Ba","Ba","Ba","Ba","Ba","Ca","Ca","Ca","Ca","Ca","Ce","Ce","Ce","Ce","Ce","Fe","Fe","Fe","Fe","Fe","Hf","Hf","Hf","Hf","Hf","K","K","K","K","K","La","La","La","La","La","Li","Li","Li","Li","Li","Mg","Mg","Mg","Mg","Mg","Mn","Mn","Mn","Mn","Mn","Na","Na","Na","Na","Na","Nd","Nd","Nd","Nd","Nd","Pb","Pb","Pb","Pb","Pb","Rb","Rb","Rb","Rb","Rb","Sr","Sr","Sr","Sr","Sr","Ti","Ti","Ti","Ti","Ti","Zr","Zr","Zr","Zr","Zr","Al","Al","Al","Al","Al","Ba","Ba","Ba","Ba","Ba","Ca","Ca","Ca","Ca","Ca","Ce","Ce","Ce","Ce","Ce","Fe","Fe","Fe","Fe","Fe","Hf","Hf","Hf","Hf","Hf","K","K","K","K","K","La","La","La","La","La","Li","Li","Li","Li","Li","Mg","Mg","Mg","Mg","Mg","Mn","Mn","Mn","Mn","Mn","Na","Na","Na","Na","Na","Nd","Nd","Nd","Nd","Nd","Pb","Pb","Pb","Pb","Pb","Rb","Rb","Rb","Rb","Rb","Sr","Sr","Sr","Sr","Sr","Ti","Ti","Ti","Ti","Ti","Zr","Zr","Zr","Zr","Zr","Al","Al","Al","Al","Al","Ba","Ba","Ba","Ba","Ba","Ca","Ca","Ca","Ca","Ca","Ce","Ce","Ce","Ce","Ce","Fe","Fe","Fe","Fe","Fe","Hf","Hf","Hf","Hf","Hf","K","K","K","K","K","La","La","La","La","La","Li","Li","Li","Li","Li","Mg","Mg","Mg","Mg","Mg","Mn","Mn","Mn","Mn","Mn","Na","Na","Na","Na","Na","Nd","Nd","Nd","Nd","Nd","Pb","Pb","Pb","Pb","Pb","Rb","Rb","Rb","Rb","Rb","Sr","Sr","Sr","Sr","Sr","Ti","Ti","Ti","Ti","Ti","Zr","Zr","Zr","Zr","Zr","Al","Al","Al","Al","Al","Ba","Ba","Ba","Ba","Ba","Ca","Ca","Ca","Ca","Ca","Ce","Ce","Ce","Ce","Ce","Fe","Fe","Fe","Fe","Fe","Hf","Hf","Hf","Hf","Hf","K","K","K","K","K","La","La","La","La","La","Li","Li","Li","Li","Li","Mg","Mg","Mg","Mg","Mg","Mn","Mn","Mn","Mn","Mn","Na","Na","Na","Na","Na","Nd","Nd","Nd","Nd","Nd","Pb","Pb","Pb","Pb","Pb","Rb","Rb","Rb","Rb","Rb","Sr","Sr","Sr","Sr","Sr","Ti","Ti","Ti","Ti","Ti","Zr","Zr","Zr","Zr","Zr","Al","Al","Al","Al","Al","Ba","Ba","Ba","Ba","Ba","Ca","Ca","Ca","Ca","Ca","Ce","Ce","Ce","Ce","Ce","Fe","Fe","Fe","Fe","Fe","Hf","Hf","Hf","Hf","Hf","K","K","K","K","K","La","La","La","La","La","Li","Li","Li","Li","Li","Mg","Mg","Mg","Mg","Mg","Mn","Mn","Mn","Mn","Mn","Na","Na","Na","Na","Na","Nd","Nd","Nd","Nd","Nd","Pb","Pb","Pb","Pb","Pb","Rb","Rb","Rb","Rb","Rb","Sr","Sr","Sr","Sr","Sr","Ti","Ti","Ti","Ti","Ti","Zr","Zr","Zr","Zr","Zr","Al","Al","Al","Al","Al","Ba","Ba","Ba","Ba","Ba","Ca","Ca","Ca","Ca","Ca","Ce","Ce","Ce","Ce","Ce","Fe","Fe","Fe","Fe","Fe","Hf","Hf","Hf","Hf","Hf","K","K","K","K","K","La","La","La","La","La","Li","Li","Li","Li","Li","Mg","Mg","Mg","Mg","Mg","Mn","Mn","Mn","Mn","Mn","Na","Na","Na","Na","Na","Nd","Nd","Nd","Nd","Nd","Pb","Pb","Pb","Pb","Pb","Rb","Rb","Rb","Rb","Rb","Sr","Sr","Sr","Sr","Sr","Ti","Ti","Ti","Ti","Ti","Zr","Zr","Zr","Zr","Zr","Al","Al","Al","Al","Al","Ba","Ba","Ba","Ba","Ba","Ca","Ca","Ca","Ca","Ca","Ce","Ce","Ce","Ce","Ce","Fe","Fe","Fe","Fe","Fe","Hf","Hf","Hf","Hf","Hf","K","K","K","K","K","La","La","La","La","La","Li","Li","Li","Li","Li","Mg","Mg","Mg","Mg","Mg","Mn","Mn","Mn","Mn","Mn","Na","Na","Na","Na","Na","Nd","Nd","Nd","Nd","Nd","Pb","Pb","Pb","Pb","Pb","Rb","Rb","Rb","Rb","Rb","Sr","Sr","Sr","Sr","Sr","Ti","Ti","Ti","Ti","Ti","Zr","Zr","Zr","Zr","Zr"],[2914,2944,2936,2926,2942,11.61,12.08,11.61,11.95,11.93,66750,68020,67160,67770,68490,9.98,9.83,9.72,9.77,9.7,679,690,691,674,660,1.21,1.101,1.339,1.37,1.2,1189,1178.9,1168.6,1187.4,1183,4.51,4.73,4.58,4.5,4.61,1.36,1.12,1.25,1.31,1.2,23950,24030,23990,24040,24330,18.77,18.03,18.55,18.36,18.21,96890,99620,99840,96970,98770,3.94,3.8,3.84,3.9,3.96,1.122,1.009,1.026,1.051,1.079,2.25,2.15,2.1,1.99,2.08,34.54,33.7,34.03,34.31,33.66,178.3,187.3,183.2,179.7,178.4,44.6,47.2,45.8,45.9,47.6,2972,2990,2968,2998,2996,11.48,11.44,11.82,11.6,11.95,68780,68110,69000,68900,68730,9.45,9.52,9.64,9.96,9.92,683,666,692,667,679,1.15,1.21,1.26,1.19,1.21,1168.6,1183.3,1193.1,1178,1188.9,4.57,4.8,4.6,4.6,4.56,1.16,1.04,0.7,1.05,0.99,24170,24210,24150,24270,24200,18.44,18.15,18.73,18.14,18.09,95870,95970,95260,96770,96160,4.01,4.04,3.72,3.7,4.02,0.949,0.978,1.031,1.054,0.963,1.92,2.05,1.88,1.98,2.01,34.88,35.02,33.95,34.68,34.66,182.3,178.1,180.5,178.8,186.5,46.3,43.9,45.3,44.8,46.2,2635,2614,2691,2671,2616,10.15,10.21,10.13,10.42,11.36,61610,62230,61090,62060,62410,9.31,9.42,9.7,9.63,9.46,684,659,712,696,680,0.92,0.89,1.02,0.94,0.88,1269,1240,1289,1268,1267,4.06,4.13,4.23,4.07,4.29,1.26,1.74,1.53,1.74,1.52,22770,22850,22870,22980,23010,18.31,18.54,17.94,18.22,18.73,102700,101000,103800,101300,103000,3.25,3.86,3.71,3.25,3.38,0.984,1.11,1.002,0.986,1.105,1.81,2.41,2.21,2.2,2.19,30.32,30.86,29.42,30.8,30.79,167.9,165.6,158.8,163.1,164.6,34.3,36.4,34.2,34.8,33.8,1623,1625.7,1628,1637,1623,12.94,13.3,13.27,13.09,13.06,69030,68960,68660,68620,68860,4.824,4.81,4.75,4.765,4.788,524.6,520.2,529.2,519.5,521.9,0.853,0.848,0.853,0.882,0.871,699.9,684,691.1,695.3,693.9,2.66,2.565,2.592,2.622,2.632,2.47,2.8,2.46,2.61,2.4,24580,24600,24420,24700,24610,127.9,128.9,129.5,129.7,129.8,105810,104790,105500,106420,105320,2.35,2.33,2.32,2.28,2.4,1.059,1.114,1.025,1.05,1.039,1.024,1.045,0.999,1.034,1.055,30.31,30.37,30.48,30.77,30.14,118.3,120.5,119.4,117.8,119.5,31.52,31.09,32.06,31.51,31.48,1702,1679.3,1669,1691,1718,13.2,13.65,12.95,12.98,13.61,69480,69330,71080,70660,70160,4.796,4.705,4.726,4.824,4.764,519.9,517.3,523.3,527.6,526.5,0.92,0.863,0.93,0.92,0.861,705.8,703.1,670.2,698.6,683.7,2.735,2.713,2.679,2.681,2.726,2.27,2.25,2.19,2.08,2.13,25060,25050,24760,25070,25110,130.5,127.7,130.2,128.5,129.5,106060,105270,103290,105390,106350,2.26,2.29,2.39,2.46,2.43,0.994,1.066,1.028,1.017,1.049,1.055,1.011,1.019,1.072,1.038,31.43,31.53,31.59,31.51,31.61,123.2,117.1,122.4,122.3,119.8,33.36,32.53,32.77,34.19,31.98,1676,1674,1672,1706,1691,12.82,13.11,13.15,12.46,13.06,69410,69790,69690,69720,70160,4.7,4.59,4.697,4.74,4.82,516.9,523.5,509,514.8,521,0.861,0.873,0.821,0.849,0.893,649.7,644,645.3,655.9,653.3,2.659,2.656,2.736,2.681,2.689,1.95,1.96,2.2,1.92,2.14,24720,24720,24710,25070,24840,128.4,128.7,126.9,128.6,128.3,101200,100680,101600,101630,101000,2.25,2.23,2.17,2.35,2.33,1.037,1.088,0.986,0.958,1.043,1.047,1.016,1.013,1.023,1.055,30.84,30.98,30.65,30.83,30.69,124.1,122,120.5,120.6,120,31.95,31.81,31.35,32.01,31.83,1680,1684,1717,1672,1676,13.31,13.88,14.17,14.15,13.99,69810,69670,71080,70180,69540,5.06,4.93,4.78,4.77,4.93,524,527,539,537,553,0.97,0.898,0.862,1.006,0.966,699.7,703.9,696.9,695.3,703.7,2.752,2.91,2.745,2.69,2.731,1.78,2.2,1.47,2.2,2.03,24590,24250,24590,25090,24780,133.2,133.4,130.3,131.7,135,103270,102360,102900,105840,102500,2.55,2.37,2.39,2.41,2.31,1.047,1.216,0.998,1.075,0.986,1.057,1.029,1.036,1.007,1.046,30.99,31.19,31.38,31.11,31.32,123.8,122.2,125,123.9,124.2,32.57,32.65,33.48,34.41,32.68,1613,1624,1621.4,1624,1616,13.26,13,12.7,11.56,13.14,67170,66770,67420,67450,66890,4.73,4.82,4.71,4.73,4.66,551,536,543,527,538,0.74,0.746,0.75,0.79,0.8,707.9,702.4,701.1,707.5,711.3,2.57,2.54,2.46,2.53,2.56,2.91,2.83,2.68,2.91,2.45,24590,24420,24120,24180,24150,125.4,126.6,127.6,124.6,125.6,106470,107150,107040,106790,105490,2.34,1.92,2.33,2.11,2.13,1.09,1.091,1.086,1.085,1.064,0.997,1.148,1.052,1.049,1.089,30.46,30.14,30.22,30.21,29.76,111.3,114.2,119.5,113.3,114.3,31.22,29.71,29.82,29.5,31.62]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>sample_id<\/th>\n      <th>element<\/th>\n      <th>ppm<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,3]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p>Your supervisor wants you to make five comparisons:</p>
<table>
<thead>
<tr>
<th style="text-align:right;">
compare_id
</th>
<th style="text-align:right;">
sample_id_1
</th>
<th style="text-align:right;">
sample_id_2
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
8
</td>
</tr>
</tbody>
</table>
<p>First, you need to take the log of the measurements, then get the mean for each sample and each element.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># take the log, then the mean of each for comparison</span>
new_samples &lt;-<span class="st"> </span><span class="kw">mutate</span>(new_samples, <span class="dt">logppm =</span> <span class="kw">log</span>(ppm)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>ppm) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(sample_id, element) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_logppm =</span> <span class="kw">mean</span>(logppm))</code></pre>
<p>Next, make each of the five comparisons. We write a function, <code>make_compare()</code> to do so, then we use <a href="https://purrr.tidyverse.org/reference/map2.html"><code>purrr::map2()</code></a> to perform the comparison for each row in <code>compare_id</code>. The resulting compared data is below.</p>
<pre class="sourceCode r"><code class="sourceCode r">make_compare &lt;-<span class="st"> </span><span class="cf">function</span>(id1, id2) {
    dat1 &lt;-<span class="st"> </span>new_samples <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(sample_id <span class="op">==</span><span class="st"> </span>id1) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(element, 
        mean_logppm)
    dat2 &lt;-<span class="st"> </span>new_samples <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(sample_id <span class="op">==</span><span class="st"> </span>id2) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">        </span><span class="kw">select</span>(element, mean_logppm)
    <span class="kw">tibble</span>(<span class="dt">element =</span> dat1<span class="op">$</span>element, <span class="dt">diff =</span> <span class="kw">abs</span>(dat1<span class="op">$</span>mean_logppm <span class="op">-</span><span class="st"> </span>dat2<span class="op">$</span>mean_logppm)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">        </span><span class="kw">spread</span>(element, diff)
}

compared &lt;-<span class="st"> </span>comparisons <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">compare =</span> <span class="kw">map2</span>(sample_id_<span class="dv">1</span>, sample_id_<span class="dv">2</span>, 
    make_compare)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">unnest</span>()

DT<span class="op">::</span><span class="kw">datatable</span>(compared) <span class="op">%&gt;%</span><span class="st"> </span>DT<span class="op">::</span><span class="kw">formatRound</span>(<span class="dv">4</span><span class="op">:</span><span class="dv">21</span>, <span class="dv">3</span>)</code></pre>
<div id="htmlwidget-a733ef7aacaf9be677d2" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-a733ef7aacaf9be677d2">{"x":{"filter":"none","data":[["1","2","3","4","5"],[1,2,3,4,5],[1,1,1,4,7],[2,3,5,6,8],[0.0177100721459063,0.103058581501238,0.550036667188176,0.034081874496664,0.0399701183161252],[0.0151641066205501,0.124980838574085,0.114838873778909,0.016422946263035,0.088726768394082],[0.0156688481162295,0.088960903838224,0.0363478740364194,0.013389996821136,0.0424920412614043],[0.0106378605388313,0.0307288640516838,0.721494338926712,0.0165355765576356,0.0339007243152225],[0.00202816712945619,0.0106558654382312,0.260783673331192,0.011639133067666,0.00565469981163957],[0.0299653782025867,0.289143230763802,0.322445970771654,0.00260696534538957,0.205105785854839],[0.000838931308894786,0.0695959105293609,0.534618423776437,0.0643763264693682,0.0087325775365894],[0.00866754908139944,0.0985269003780311,0.527114271057596,0.0264463602929953,0.0880026442417127],[0.245320005545487,0.21731087746052,0.561359166919284,0.225291131039603,0.362332282844895],[0.00548365634915093,0.0499127070001819,0.0383953186471082,0.00930446612386504,0.0150017288728304],[0.00402278328188954,0.00197095441127226,1.95056530985033,0.00761468625170547,0.0522384787398478],[0.0247428978257513,0.0393020540184352,0.0673547157366379,0.0420324901719162,0.0306768268606241],[0.00189991776277831,0.110397994553901,0.497122426190664,0.0307104793515487,0.107199328420168],[0.0609378749481826,0.0199084053488238,0.025062441291944,0.0342511737384514,0.0203347105107558],[0.0712339225451224,0.0198934153935468,0.709742725387129,0.000541938901203746,0.0294937579202234],[0.0171731543760618,0.112191533884853,0.0766568046091063,0.0125630146235323,0.0339218657765947],[0.000729169783627803,0.100720689555393,0.40512843606776,0.0194144298974104,0.0783290873430138],[0.0200316939741212,0.286738351777798,0.337926405859599,0.00816994667583337,0.0878786402815104]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>compare_id<\/th>\n      <th>sample_id_1<\/th>\n      <th>sample_id_2<\/th>\n      <th>Al<\/th>\n      <th>Ba<\/th>\n      <th>Ca<\/th>\n      <th>Ce<\/th>\n      <th>Fe<\/th>\n      <th>Hf<\/th>\n      <th>K<\/th>\n      <th>La<\/th>\n      <th>Li<\/th>\n      <th>Mg<\/th>\n      <th>Mn<\/th>\n      <th>Na<\/th>\n      <th>Nd<\/th>\n      <th>Pb<\/th>\n      <th>Rb<\/th>\n      <th>Sr<\/th>\n      <th>Ti<\/th>\n      <th>Zr<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false,"rowCallback":"function(row, data) {\nDTWidget.formatRound(this, row, data, 4, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 5, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 6, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 7, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 8, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 9, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 10, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 11, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 12, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 13, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 14, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 15, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 16, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 17, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 18, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 19, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 20, 3, 3, ',', '.');\nDTWidget.formatRound(this, row, data, 21, 3, 3, ',', '.');\n}"}},"evals":["options.rowCallback"],"jsHooks":[]}</script>
<p>Finally, we take the compared data and predict using the random forest object:</p>
<pre class="sourceCode r"><code class="sourceCode r">newpred &lt;-<span class="st"> </span><span class="kw">predict</span>(RF_classifier, <span class="dt">newdata =</span> compared, <span class="dt">type =</span> <span class="st">&quot;prob&quot;</span>)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># only take the id data from compare, and the M prediction from newpred</span>
<span class="kw">bind_cols</span>(compared[, <span class="dv">1</span><span class="op">:</span><span class="dv">3</span>], <span class="dt">score =</span> newpred[, <span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">prediction =</span> <span class="kw">ifelse</span>(score <span class="op">&gt;</span><span class="st"> </span>
<span class="st">    </span><span class="fl">0.5</span>, <span class="st">&quot;M&quot;</span>, <span class="st">&quot;NM&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span>knitr<span class="op">::</span><span class="kw">kable</span>(<span class="dt">format =</span> <span class="st">&quot;html&quot;</span>, <span class="dt">caption =</span> <span class="st">&quot;Predicted scores of new comparison cases from the random forest classifier&quot;</span>, 
    <span class="dt">longtable =</span> <span class="ot">FALSE</span>, <span class="dt">row.names =</span> <span class="ot">FALSE</span>, <span class="dt">digits =</span> <span class="dv">3</span>, <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;Comparison ID&quot;</span>, 
        <span class="st">&quot;Sample ID 1&quot;</span>, <span class="st">&quot;Sample ID 2&quot;</span>, <span class="st">&quot;Score&quot;</span>, <span class="st">&quot;Decision&quot;</span>))</code></pre>
<table>
<caption>
<span id="tab:newtesttable">Table 7.3: </span>Predicted scores of new comparison cases from the random forest classifier
</caption>
<thead>
<tr>
<th style="text-align:right;">
Comparison ID
</th>
<th style="text-align:right;">
Sample ID 1
</th>
<th style="text-align:right;">
Sample ID 2
</th>
<th style="text-align:right;">
Score
</th>
<th style="text-align:left;">
Decision
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.812
</td>
<td style="text-align:left;">
M
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.238
</td>
<td style="text-align:left;">
NM
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:left;">
NM
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0.430
</td>
<td style="text-align:left;">
NM
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0.618
</td>
<td style="text-align:left;">
M
</td>
</tr>
</tbody>
</table>
<!--For comparison 1 the RF score are over 0.9, meaning the RF is 90% sure about the source of these comparisons to be same pane. The comparison 3 is comparing a pair of glass fragments from panes produced in different manufacturers. In this case, the RF score is zero. The comparison 4 and 5 is non-mated pairs from two different panes but very closed produced (within 2 days) in the same manufacturer. For comparison 4, the RF score is 0.16, so that it clearly indicates the source toward the different source. For comparison 5, the RF score is 0.56 which is unclear to declare one of hypotheses either same source or different source. -->
<p>Table <a href="glass.html#tab:newtesttable">7.3</a> shows the RF score which is defined as the empirical class probability that the samples are from the same pane (M) by the RF algorithm<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a>. Based on these scores, it appears that samples 1 and 2 are very likely from the same source, while samples 1 and 5 are very likely from different sources. Using a threshold of 0.5, sample 4 and sample 6 are predicted to be from different sources. However, this score is so close to the threshold of 0.5 that we may want to say this is inconclusive.<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a> Samples 1 and 3 are probably from different sources, though we are less confident in that determination than we are in the decision that samples 1 and 5 are from different sources. Finally, samples 7 and 8 are probably from the same source, but we are less certain of this than we are that samples 1 and 2 are from the same source.</p>
<p>More research into the appropriateness of this random forest method for making glass source conclusions is needed. Important points to consider are:</p>
<ul>
<li>What database should be used to train the algorithm?</li>
<li>Could the random forest method over fit, reducing the generalizability of this method?</li>
</ul>
<p>Nevertheless, the RF classifier makes good use of the glass fragment data, with its high dimension and small number of repeated measurements. More details on the RF classifier and additional discussion can be found in <span class="citation">Park and Carriquiry (<a href="#ref-park2018">2019</a><a href="#ref-park2018">a</a>)</span>.</p>
<p><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/us/"><img alt="Creative Commons License" style="border-width:0; display: block; margin-left: auto; margin-right: auto;" src="https://i.creativecommons.org/l/by-nc-nd/3.0/us/88x31.png" /></a></p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-curranbook">
<p>Curran, James Michael, Tacha Natalie Hicks, and John S. Buckleton. 2000. <em>Forensic Interpretation of Glass Evidence</em>. CRC Press.</p>
</div>
<div id="ref-hop">
<p>Cook, Roger, Ian W Evett, Graham Jackson, PJ Jones, and JA Lambert. 1998. “A Hierarchy of Propositions: Deciding Which Level to Address in Casework.” <em>Science &amp; Justice</em> 38 (4): 231–39.</p>
</div>
<div id="ref-ASTME233012">
<p>ASTM-E2330-12. 2012. “Standard Test Method for Determination of Concentrations of Elements in Glass Samples Using Inductively Coupled Plasma Mass Spectrometry (ICP-MS) for Forensic Comparisons, Retrieved from Https://Doi.org/10.1520/E2330-12.” ASTM International.</p>
</div>
<div id="ref-ASTME292716">
<p>ASTM-E2927-16. 2016. “Standard Test Method for Determination of Trace Elements in Soda-Lime Glass Samples Using Laser Ablation Inductively Coupled Plasma Mass Spectrometry for Forensic Comparisons, Retrieved from Https://Doi.org/10.1520/E2927-16.” ASTM International.</p>
</div>
<div id="ref-glassbackground">
<p>Bottrell, Maureen C. 2009. “Forensic Glass Comparison: Background Information Used in Data Interpretation. (Report).” <em>Forensic Science Communications</em> 11 (2). <a href="https://archives.fbi.gov/archives/about-us/lab/forensic-science-communications/fsc/april2009/review">https://archives.fbi.gov/archives/about-us/lab/forensic-science-communications/fsc/april2009/review</a>.</p>
</div>
<div id="ref-park2018">
<p>Park, Soyoung, and Alicia Carriquiry. 2019a. “Learning Algorithms to Evaluate Forensic Glass Evidence.” <em>Annals of Applied Statistics</em>. <a href="https://www.e-publications.org/ims/submission/AOAS/user/submissionFile/36724?confirm=02d8a608">https://www.e-publications.org/ims/submission/AOAS/user/submissionFile/36724?confirm=02d8a608</a>.</p>
</div>
<div id="ref-weisglass">
<p>Weis, Peter, Marc Dücking, Peter Watzke, Sonja Menges, and Stefan Becker. 2011. “Establishing a match criterion in forensic comparison analysis of float glass using laser ablation inductively coupled plasma mass spectrometry.” <em>Journal of Analytical Atomic Spectrometry</em> 26 (6): 1273–84. <a href="https://doi.org/10.1039/c0ja00168f">https://doi.org/10.1039/c0ja00168f</a>.</p>
</div>
<div id="ref-R-caret">
<p>Jed Wing, Max Kuhn. Contributions from, Steve Weston, Andre Williams, Chris Keefer, Allan Engelhardt, Tony Cooper, Zachary Mayer, et al. 2018. <em>Caret: Classification and Regression Training</em>. <a href="https://CRAN.R-project.org/package=caret">https://CRAN.R-project.org/package=caret</a>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="6">
<li id="fn6"><p>In fact, we do know the truth here: for comparisons (1, 2, 3, 4, 5), the truth is (M, NM, NM, M, M).<a href="glass.html#fnref6" class="footnote-back">↩</a></p></li>
<li id="fn7"><p>See this discussion of “equivocal zones:” <a href="http://appliedpredictivemodeling.com/blog/2013/8/15/equivocal-zones" class="uri">http://appliedpredictivemodeling.com/blog/2013/8/15/equivocal-zones</a><a href="glass.html#fnref7" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="shoe.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="decision-making.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/sctyner/OpenForSciR/edit/master/content/content/trace-glass.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["open-forensic-science-in-r.pdf", "open-forensic-science-in-r.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
